echo 'FILE NO LONGER USED.'
echo ' '
echo 'INSTEAD USE'
echo 'GitDate.sh'
echo 'From previous Dir'
echo ' '
echo 'e.g.,'
echo ' cd G....'
echo 'NOT'
echo 'cd git-....'
echo 'then ..'
echo './G....'
echo 'NOT'
echo './git-date...'
echo ' '
